# Generated by Django 3.2.6 on 2021-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactpoint_contactpointmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
