# Generated by Django 3.2.6 on 2021-08-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210813_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='contact_point_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contactpointmethod'),
        ),
    ]
