# Generated by Django 3.2.6 on 2021-08-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210813_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ContactTag',
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactpointmethod',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactpointmethod',
            name='hours_for_response',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpointmethod',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
