# Generated by Django 3.2.6 on 2021-08-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210813_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tags',
            new_name='contact_tags',
        ),
    ]
