# Generated by Django 3.2.6 on 2021-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_tags_contact_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpoint',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Sent', 'Sent'), ('Responded - reply', 'Responded - reply'), ('Responded - done', 'Responded - done')], max_length=100, null=True),
        ),
    ]
