# Generated by Django 3.2.6 on 2021-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_contactpoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='times_used',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
