# Generated by Django 3.2.6 on 2021-08-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210814_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwrapper',
            name='name',
        ),
    ]
