# Generated by Django 3.2.6 on 2021-08-14 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userwrapper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpointmethod',
            name='user_wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userwrapper'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='user_wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userwrapper'),
        ),
    ]
